// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -emit-llvm -o - -flegacy-pass-manager -O0 %s \
// RUN:   | FileCheck --check-prefix=O0-NO-MEM2REG
// RUN: %clang_cc1 -triple riscv64 -emit-llvm -o - -fno-legacy-pass-manager -O0 %s \
// RUN:   | FileCheck --check-prefix=O0-NO-MEM2REG
// RUN: %clang_cc1 -triple riscv64 -emit-llvm -o - -flegacy-pass-manager -O0 -fno-always-mem2reg %s \
// RUN:   | FileCheck --check-prefix=O0-NO-MEM2REG
// RUN: %clang_cc1 -triple riscv64 -emit-llvm -o - -fno-legacy-pass-manager -O0 -fno-always-mem2reg %s \
// RUN:   | FileCheck --check-prefix=O0-NO-MEM2REG
// RUN: %clang_cc1 -triple riscv64 -emit-llvm -o - -flegacy-pass-manager -O0 -falways-mem2reg %s \
// RUN:   | FileCheck --check-prefix=O0-MEM2REG
// RUN: %clang_cc1 -triple riscv64 -emit-llvm -o - -fno-legacy-pass-manager -O0 -falways-mem2reg %s \
// RUN:   | FileCheck --check-prefix=O0-MEM2REG

// O0-NO-MEM2REG-LABEL: @add(
// O0-NO-MEM2REG-NEXT:  entry:
// O0-NO-MEM2REG-NEXT:    [[A_ADDR:%.*]] = alloca i32, align 4
// O0-NO-MEM2REG-NEXT:    [[B_ADDR:%.*]] = alloca i32, align 4
// O0-NO-MEM2REG-NEXT:    store i32 [[A:%.*]], i32* [[A_ADDR]], align 4
// O0-NO-MEM2REG-NEXT:    store i32 [[B:%.*]], i32* [[B_ADDR]], align 4
// O0-NO-MEM2REG-NEXT:    [[TMP0:%.*]] = load i32, i32* [[A_ADDR]], align 4
// O0-NO-MEM2REG-NEXT:    [[TMP1:%.*]] = load i32, i32* [[B_ADDR]], align 4
// O0-NO-MEM2REG-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP0]], [[TMP1]]
// O0-NO-MEM2REG-NEXT:    ret i32 [[ADD]]
//
// O0-MEM2REG-LABEL: @add(
// O0-MEM2REG-NEXT:  entry:
// O0-MEM2REG-NEXT:    [[ADD:%.*]] = add nsw i32 [[A:%.*]], [[B:%.*]]
// O0-MEM2REG-NEXT:    ret i32 [[ADD]]
//
int add(int a, int b) {
  return a + b;
}
